from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import relationship
from flask.ext.login import UserMixin
from campaign import db

class JSONifiableModel(object):
    def to_dict(self):
        cols = [ col.name for col in self.__table__.columns ]
        return {self.__class__.__name__:dict(zip(cols, [ getattr(self, col) for col in cols ]))}

class MapObject(db.Model, JSONifiableModel):
    __tablename__ = 'map_objects'
    id = db.Column(db.Integer, primary_key=True)
    x = db.Column(db.Integer)
    y = db.Column(db.Integer)
    type = db.Column(db.String(32), nullable=False)
    __mapper_args__ = {'polymorphic_on' : type}

class Terrain(MapObject):
    __tablename__ = 'terrains'
    __mapper_args__ = {'polymorphic_identity' : 'terrain'}
    terrain_id = db.Column(db.Integer, db.ForeignKey('map_objects.id'), primary_key=True)
    terrain_type = db.Column(db.String(32), nullable=False)

    def __init__(self, x, y, terrain):
        self.x = x
        self.y = y
        self.terrain_type = terrain

class Ship(MapObject):
    __tablename__ = 'ships'
    __mapper_args__ = {'polymorphic_identity' : 'ship'}
    ship_id = db.Column(db.Integer, db.ForeignKey('map_objects.id'), primary_key=True)
    model_id = db.Column(db.Integer, db.ForeignKey('shiplist.id'))

class ShipModel(db.Model, JSONifiableModel):
    __tablename__ = 'shiplist'
    id = db.Column(db.Integer, primary_key=True)
    instances = relationship("Ship", backref='model')

    race = db.Column(db.String(64))
    hull_type = db.Column(db.String(64))
    ship_class = db.Column(db.String(64))
    class_type = db.Column(db.String(64))
    bpv = db.Column(db.String(64))
    special_role = db.Column(db.String(64))
    year_first_available = db.Column(db.String(64))
    year_last_available = db.Column(db.String(64))
    size_class = db.Column(db.String(64))
    turn_mode = db.Column(db.String(64))
    move_cost = db.Column(db.String(64))
    het_2_turns_nimble = db.Column(db.String(64))
    het_breakdown = db.Column(db.String(64))
    stealth_ecm = db.Column(db.String(64))
    regular_crew = db.Column(db.String(64))
    boarding_parties_base = db.Column(db.String(64))
    boarding_parties_max = db.Column(db.String(64))
    deck_crews = db.Column(db.String(64))
    total_crew = db.Column(db.String(64))
    min_crew = db.Column(db.String(64))
    shield_1 = db.Column(db.String(64))
    shield_2___6 = db.Column(db.String(64))
    shield_3___5 = db.Column(db.String(64))
    shield_4 = db.Column(db.String(64))
    shield_total = db.Column(db.String(64))
    cloak = db.Column(db.String(64))
    heavy_weapon_1_num = db.Column(db.String(64))
    heavy_weapon_1 = db.Column(db.String(64))
    heavy_weapon_1_arc = db.Column(db.String(64))
    heavy_weapon_2_num = db.Column(db.String(64))
    heavy_weapon_2 = db.Column(db.String(64))
    heavy_weapon_2_arc = db.Column(db.String(64))
    heavy_weapon_3_num = db.Column(db.String(64))
    heavy_weapon_3 = db.Column(db.String(64))
    heavy_weapon_3_arc = db.Column(db.String(64))
    heavy_weapon_4_num = db.Column(db.String(64))
    heavy_weapon_4 = db.Column(db.String(64))
    heavy_weapon_4_arc = db.Column(db.String(64))
    heavy_weapon_5_num = db.Column(db.String(64))
    heavy_weapon_5 = db.Column(db.String(64))
    heavy_weapon_5_arc = db.Column(db.String(64))
    heavy_weapon_6_num = db.Column(db.String(64))
    heavy_weapon_6 = db.Column(db.String(64))
    heavy_weapon_6_arc = db.Column(db.String(64))
    heavy_weapon_7_num = db.Column(db.String(64))
    heavy_weapon_7 = db.Column(db.String(64))
    heavy_weapon_7_arc = db.Column(db.String(64))
    heavy_weapon_8_num = db.Column(db.String(64))
    heavy_weapon_8 = db.Column(db.String(64))
    heavy_weapon_8_arc = db.Column(db.String(64))
    heavy_weapon_9_num = db.Column(db.String(64))
    heavy_weapon_9 = db.Column(db.String(64))
    heavy_weapon_9_arc = db.Column(db.String(64))
    heavy_weapon_10_num = db.Column(db.String(64))
    heavy_weapon_10 = db.Column(db.String(64))
    heavy_weapon_10_arc = db.Column(db.String(64))
    weapon_11_num = db.Column(db.String(64))
    weapon_11 = db.Column(db.String(64))
    weapon_11_arc = db.Column(db.String(64))
    weapon_12_num = db.Column(db.String(64))
    weapon_12 = db.Column(db.String(64))
    weapon_12_arc = db.Column(db.String(64))
    weapon_13_num = db.Column(db.String(64))
    weapon_13 = db.Column(db.String(64))
    weapon_13_arc = db.Column(db.String(64))
    weapon_14_num = db.Column(db.String(64))
    weapon_14 = db.Column(db.String(64))
    weapon_14_arc = db.Column(db.String(64))
    weapon_15_num = db.Column(db.String(64))
    weapon_15 = db.Column(db.String(64))
    weapon_15_arc = db.Column(db.String(64))
    weapon_16_num = db.Column(db.String(64))
    weapon_16 = db.Column(db.String(64))
    weapon_16_arc = db.Column(db.String(64))
    weapon_17_num = db.Column(db.String(64))
    weapon_17 = db.Column(db.String(64))
    weapon_17_arc = db.Column(db.String(64))
    weapon_18_num = db.Column(db.String(64))
    weapon_18 = db.Column(db.String(64))
    weapon_18_arc = db.Column(db.String(64))
    weapon_19_num = db.Column(db.String(64))
    weapon_19 = db.Column(db.String(64))
    weapon_19_arc = db.Column(db.String(64))
    weapon_20_num = db.Column(db.String(64))
    weapon_20 = db.Column(db.String(64))
    weapon_20_arc = db.Column(db.String(64))
    weapon_21_num = db.Column(db.String(64))
    weapon_21 = db.Column(db.String(64))
    weapon_21_arc = db.Column(db.String(64))
    weapon_22_num = db.Column(db.String(64))
    weapon_22 = db.Column(db.String(64))
    weapon_22_arc = db.Column(db.String(64))
    weapon_23_num = db.Column(db.String(64))
    weapon_23 = db.Column(db.String(64))
    weapon_23_arc = db.Column(db.String(64))
    weapon_24_num = db.Column(db.String(64))
    weapon_24 = db.Column(db.String(64))
    weapon_24_arc = db.Column(db.String(64))
    weapon_25_num = db.Column(db.String(64))
    weapon_25 = db.Column(db.String(64))
    weapon_25_arc = db.Column(db.String(64))
    probes = db.Column(db.String(64))
    t_bombs_base = db.Column(db.String(64))
    t_bombs_max = db.Column(db.String(64))
    nuclear_mine_base = db.Column(db.String(64))
    nuclear_mine_max = db.Column(db.String(64))
    drone_control = db.Column(db.String(64))
    add_6 = db.Column(db.String(64))
    add_12 = db.Column(db.String(64))
    shuttles_size = db.Column(db.String(64))
    launch_rate = db.Column(db.String(64))
    general_base = db.Column(db.String(64))
    general_max = db.Column(db.String(64))
    fighter_bay_1 = db.Column(db.String(64))
    fighter_type_1 = db.Column(db.String(64))
    fighter_bay_2 = db.Column(db.String(64))
    fighter_type_2 = db.Column(db.String(64))
    fighter_bay_3 = db.Column(db.String(64))
    fighter_type_3 = db.Column(db.String(64))
    fighter_bay_4 = db.Column(db.String(64))
    fighter_type_4 = db.Column(db.String(64))
    armor = db.Column(db.String(64))
    forward_hull = db.Column(db.String(64))
    center_hull = db.Column(db.String(64))
    aft_hull = db.Column(db.String(64))
    cargo = db.Column(db.String(64))
    barracks = db.Column(db.String(64))
    repair = db.Column(db.String(64))
    r_l_warp = db.Column(db.String(64))
    c_warp = db.Column(db.String(64))
    impulse = db.Column(db.String(64))
    apr = db.Column(db.String(64))
    battery = db.Column(db.String(64))
    bridge = db.Column(db.String(64))
    security = db.Column(db.String(64))
    lab = db.Column(db.String(64))
    transporters = db.Column(db.String(64))
    tractors = db.Column(db.String(64))
    mech_tractors = db.Column(db.String(64))
    special_sensors = db.Column(db.String(64))
    sensors = db.Column(db.String(64))
    scanners = db.Column(db.String(64))
    explosion_strength = db.Column(db.String(64))
    acceleration = db.Column(db.String(64))
    damage_control = db.Column(db.String(64))
    extra_damage = db.Column(db.String(64))
    ship_cost = db.Column(db.String(64))
    refit_base_class = db.Column(db.String(64))
    geometry = db.Column(db.String(64))
    ui = db.Column(db.String(64))
    full_name = db.Column(db.String(64))
    refits = db.Column(db.String(64))
    balance = db.Column(db.String(64))
    end = db.Column(db.String(64))
    w1 = db.Column(db.String(64))
    w2 = db.Column(db.String(64))
    w3 = db.Column(db.String(64))
    w4 = db.Column(db.String(64))
    w5 = db.Column(db.String(64))
    w6 = db.Column(db.String(64))
    w7 = db.Column(db.String(64))
    w8 = db.Column(db.String(64))
    w9 = db.Column(db.String(64))
    w10 = db.Column(db.String(64))
    w11 = db.Column(db.String(64))
    w12 = db.Column(db.String(64))
    w13 = db.Column(db.String(64))
    w14 = db.Column(db.String(64))
    w15 = db.Column(db.String(64))
    w16 = db.Column(db.String(64))
    w17 = db.Column(db.String(64))
    w18 = db.Column(db.String(64))
    w19 = db.Column(db.String(64))
    w20 = db.Column(db.String(64))
    w21 = db.Column(db.String(64))
    w22 = db.Column(db.String(64))
    w23 = db.Column(db.String(64))
    w24 = db.Column(db.String(64))
    w25 = db.Column(db.String(64))
    weapon_bpv = db.Column(db.String(64))
    fb1 = db.Column(db.String(64))
    fb2 = db.Column(db.String(64))
    fb3 = db.Column(db.String(64))
    fb4 = db.Column(db.String(64))
    fighter_subtotal = db.Column(db.String(64))
    system_bpv = db.Column(db.String(64))
    bpv_subtotal = db.Column(db.String(64))
    yfa = db.Column(db.String(64))
    yla = db.Column(db.String(64))
    enhanced_class_type = db.Column(db.String(64))
    role = db.Column(db.String(64))
    secondary_role = db.Column(db.String(64))
    xtech = db.Column(db.String(64))
    productionavailability = db.Column(db.String(64))
